package org.fuusio.api.mvp;

import android.view.View;

/**
 * {@link PresenterDelegate} delegates {@link View} events to a {@link Presenter}. Concrete implementations
 * are generated by Fuusio API Compiler.
 */
public abstract class PresenterDelegate<T_Presenter extends Presenter> {

    protected final T_Presenter mPresenter;

    protected PresenterDelegate(final T_Presenter presenter) {
        mPresenter = presenter;
    }

    protected abstract void onClick(String tag);

    protected abstract void onTextChanged(String tag, String text);
}
