package com.robopupu.api.mvp;

import android.view.View;

/**
 * {@link PresenterDelegate} delegates {@link View} events to a {@link Presenter}. Concrete implementations
 * are generated by Robopupu Compiler.
 */
public abstract class PresenterDelegate<T_Presenter extends Presenter> {

    protected final T_Presenter presenter;

    protected PresenterDelegate(final T_Presenter presenter) {
        this.presenter = presenter;
    }

    protected abstract void onChecked(String tag, boolean checked);

    protected abstract void onClick(String tag);

    protected abstract void onTextChanged(String tag, String text);
}
